import {Anek_Bangla} from "next/font/google"
import type { Metadata } from "next";

import "./globals.css";
import Nav from "./components/Nav";


export const metadata: Metadata = {
  title: "Mango",
  description: "Generated by Mazaharul islam ",
};



const siteFont=Anek_Bangla({weight:"500",style:"normal",subsets:["bengali"]})

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body
        className={`${siteFont.className} antialiased`}
      >
        <Nav/>
     <div className="w-[85%] mx-auto">
     {children}
     </div>
      </body>
    </html>
  );
}
